# Generated by Django 4.2.7 on 2023-11-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=255, unique=True, verbose_name='软件账号')),
                ('password', models.CharField(max_length=255, verbose_name='软件密码')),
                ('team', models.CharField(blank=True, max_length=255, null=True, verbose_name='部门')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('updated', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统账号管理',
                'verbose_name_plural': '系统账号管理',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='ActionConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField(verbose_name='自动化操作配置')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '自动化操作配置',
                'verbose_name_plural': '自动化操作配置',
                'db_table': 'action',
            },
        ),
    ]
