# Generated by Django 4.2.7 on 2023-11-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255, verbose_name='客户电话')),
                ('customername', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户名称')),
                ('labels1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标签1')),
                ('labels2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标签2')),
                ('labels3', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标签3')),
                ('labels4', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标签4')),
                ('labels5', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='标签5')),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='软件账号')),
                ('team', models.CharField(blank=True, max_length=255, null=True, verbose_name='部门')),
                ('interval', models.IntegerField(default=0, verbose_name='定时发送间隔（小时）')),
                ('status', models.IntegerField(choices=[(0, '待发送'), (1, '已发送')], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户管理',
                'verbose_name_plural': '客户管理',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='', verbose_name='标签')),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='账号')),
                ('team', models.CharField(blank=True, max_length=255, null=True, verbose_name='部门')),
                ('level', models.IntegerField(choices=[(1, '一级'), (2, '二级')], default=1, verbose_name='类别')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('updated', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签管理',
                'verbose_name_plural': '标签管理',
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.IntegerField(default=0, verbose_name='群发信息数')),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='账号')),
                ('team', models.CharField(blank=True, max_length=255, null=True, verbose_name='部门')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('updated', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据记录',
                'verbose_name_plural': '数据记录',
                'db_table': 'record',
            },
        ),
    ]
